t1 = 0
t2 = 1
termos = 3
n = int(input('Quantos termos você quer mostrar? '))
print(f'{t1} ► {t2}', end='')
while termos <= n:
    t3 = t1 + t2
    print(f' ► {t3}', end='')
    t1 = t2
    t2 = t3
    termos += 1
